import { getProductRepository } from '../../RepositoryFactory';
import { createRepositoryFacade } from './createRepositoryFacade';

export const {
  saveProductsBulk,
  saveBatchesBulk,
  updateBatchesBulk,
  getAllBatches,
  getAllBatchesCache,
  getBatchCacheById,
  getLatestBatchForProduct,
  getBatchesForProduct,
  getProductByBarcode,
  updateProduct,
  getAllProducts,
  updateProductsBulk,
  getAllProductsCache,
  getProductCacheByBarcode,
  getProductCacheById,
  updateProductsCacheBulk,
  deleteProductsCacheByIds,
  deleteBatchesCacheByIds,
  updateProductsCacheStock,
  addLocalBatchCache,
  upsertLocalProduct,
  getLocalProducts,
  getLocalProductById,
  deleteLocalProduct,
} = createRepositoryFacade(() => getProductRepository(), [
  'saveProductsBulk',
  'saveBatchesBulk',
  'updateBatchesBulk',
  'getAllBatches',
  'getAllBatchesCache',
  'getBatchCacheById',
  'getLatestBatchForProduct',
  'getBatchesForProduct',
  'getProductByBarcode',
  'updateProduct',
  'getAllProducts',
  'updateProductsBulk',
  'getAllProductsCache',
  'getProductCacheByBarcode',
  'getProductCacheById',
  'updateProductsCacheBulk',
  'deleteProductsCacheByIds',
  'deleteBatchesCacheByIds',
  'updateProductsCacheStock',
  'addLocalBatchCache',
  'upsertLocalProduct',
  'getLocalProducts',
  'getLocalProductById',
  'deleteLocalProduct',
]);
