import { getStaffRepository } from '../../RepositoryFactory';
import { createRepositoryFacade } from './createRepositoryFacade';

export const {
  upsertLocalStaff,
  getLocalStaff,
  getLocalStaffById,
  deleteLocalStaff,
  upsertLocalSalary,
  getLocalSalaries,
  getLocalSalaryById,
  deleteLocalSalary,
  upsertLocalExpense,
  getLocalExpenses,
  getLocalExpenseById,
  deleteLocalExpense,
  getStaffRecords,
  getSalaryRecords,
  getExpenseRecords,
  putStaffRecord,
  putSalaryRecord,
  putExpenseRecord,
  runStaffSalariesExpensesTransaction,
  mergeRemoteStaffRecords,
  mergeRemoteSalaryRecords,
  mergeRemoteExpenseRecords,
} = createRepositoryFacade(() => getStaffRepository(), [
  'upsertLocalStaff',
  'getLocalStaff',
  'getLocalStaffById',
  'deleteLocalStaff',
  'upsertLocalSalary',
  'getLocalSalaries',
  'getLocalSalaryById',
  'deleteLocalSalary',
  'upsertLocalExpense',
  'getLocalExpenses',
  'getLocalExpenseById',
  'deleteLocalExpense',
  'getStaffRecords',
  'getSalaryRecords',
  'getExpenseRecords',
  'putStaffRecord',
  'putSalaryRecord',
  'putExpenseRecord',
  'runStaffSalariesExpensesTransaction',
  'mergeRemoteStaffRecords',
  'mergeRemoteSalaryRecords',
  'mergeRemoteExpenseRecords',
]);
