import { getSupplierRepository } from '../../RepositoryFactory';
import { createRepositoryFacade } from './createRepositoryFacade';

export const {
  updateSuppliersCacheBulk,
  getAllSuppliersCache,
  getSupplierCacheById,
  deleteSuppliersCacheByIds,
  upsertSupplierLedgerEntry,
  upsertSupplierLedgerBulk,
  getSupplierLedgerBySupplierId,
  dedupeSuppliersCache,
  upsertLocalSupplier,
  getLocalSuppliers,
  getLocalSupplierById,
  deleteLocalSupplier,
  searchSuppliers,
  getSupplierById,
  getSupplierLedgerDetail,
  createSupplier,
  updateSupplier,
  deleteSupplier,
} = createRepositoryFacade(() => getSupplierRepository(), [
  'updateSuppliersCacheBulk',
  'getAllSuppliersCache',
  'getSupplierCacheById',
  'deleteSuppliersCacheByIds',
  'upsertSupplierLedgerEntry',
  'upsertSupplierLedgerBulk',
  'getSupplierLedgerBySupplierId',
  'dedupeSuppliersCache',
  'upsertLocalSupplier',
  'getLocalSuppliers',
  'getLocalSupplierById',
  'deleteLocalSupplier',
  'searchSuppliers',
  'getSupplierById',
  'getSupplierLedgerDetail',
  'createSupplier',
  'updateSupplier',
  'deleteSupplier',
]);
